services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    volumes:
      - ..:/workspaces
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  selenium:
    image: selenium/standalone-firefox:4.16.1-20231212
    shm_size: 10gb
    ports:
      - 4444:4444
      - 7900:7900
    depends_on:
      - api
